#!/usr/bin/env bash
# Bring up the Prexel dev environment.
#
# Notes:
#  - The `prexel` service in deployments/docker-compose.yml bind-mounts the
#    host Docker socket at /var/run/docker.sock. This grants the container
#    root-equivalent access to the host's Docker daemon — desired for managing
#    test app containers, but worth flagging.
#  - Default ports: 3000 (Prexel HTTPS), 5173 (Vue HMR), 80/443 (Caddy),
#    2019 (Caddy admin, host loopback only).
#  - First start pulls images and compiles Go — give it a minute.
#  - First start also generates ../.env.dev with random secrets. That file is
#    gitignored — never commit it. See .env.dev.example for the schema.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="$REPO_ROOT/deployments/docker-compose.yml"
ENV_DEV="$REPO_ROOT/.env.dev"

if [[ ! -f "$ENV_DEV" ]]; then
    echo "==> generating $ENV_DEV with random dev secrets"
    if ! command -v openssl >/dev/null 2>&1; then
        echo "openssl required to generate dev secrets; install it and retry" >&2
        exit 1
    fi
    umask 077
    cat > "$ENV_DEV" <<EOF
# Auto-generated by scripts/dev-up.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Local dev only. Never commit this file. Regenerate by deleting it and
# re-running scripts/dev-up.sh up.
PREXEL_SECRET_KEY=$(openssl rand -hex 32)
PREXEL_JWT_SECRET=$(openssl rand -hex 32)
EOF
fi

cd "$REPO_ROOT"
exec docker compose -f "$COMPOSE_FILE" "$@"
